// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package com.hualala.app.wechat.grpc;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string traceID = 1;</code>
     */
    java.lang.String getTraceID();
    /**
     * <code>optional string traceID = 1;</code>
     */
    com.google.protobuf.ByteString
        getTraceIDBytes();
  }
  /**
   * Protobuf type {@code RequestHeader}
   */
  public  static final class RequestHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestHeader)
      RequestHeaderOrBuilder {
    // Use RequestHeader.newBuilder() to construct.
    private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestHeader() {
      traceID_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              traceID_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hualala.app.wechat.grpc.Common.internal_static_RequestHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hualala.app.wechat.grpc.Common.internal_static_RequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hualala.app.wechat.grpc.Common.RequestHeader.class, com.hualala.app.wechat.grpc.Common.RequestHeader.Builder.class);
    }

    public static final int TRACEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object traceID_;
    /**
     * <code>optional string traceID = 1;</code>
     */
    public java.lang.String getTraceID() {
      java.lang.Object ref = traceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string traceID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIDBytes() {
      java.lang.Object ref = traceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTraceIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceID_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTraceIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceID_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hualala.app.wechat.grpc.Common.RequestHeader)) {
        return super.equals(obj);
      }
      com.hualala.app.wechat.grpc.Common.RequestHeader other = (com.hualala.app.wechat.grpc.Common.RequestHeader) obj;

      boolean result = true;
      result = result && getTraceID()
          .equals(other.getTraceID());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceID().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hualala.app.wechat.grpc.Common.RequestHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestHeader)
        com.hualala.app.wechat.grpc.Common.RequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hualala.app.wechat.grpc.Common.internal_static_RequestHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hualala.app.wechat.grpc.Common.internal_static_RequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hualala.app.wechat.grpc.Common.RequestHeader.class, com.hualala.app.wechat.grpc.Common.RequestHeader.Builder.class);
      }

      // Construct using com.hualala.app.wechat.grpc.Common.RequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        traceID_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hualala.app.wechat.grpc.Common.internal_static_RequestHeader_descriptor;
      }

      public com.hualala.app.wechat.grpc.Common.RequestHeader getDefaultInstanceForType() {
        return com.hualala.app.wechat.grpc.Common.RequestHeader.getDefaultInstance();
      }

      public com.hualala.app.wechat.grpc.Common.RequestHeader build() {
        com.hualala.app.wechat.grpc.Common.RequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hualala.app.wechat.grpc.Common.RequestHeader buildPartial() {
        com.hualala.app.wechat.grpc.Common.RequestHeader result = new com.hualala.app.wechat.grpc.Common.RequestHeader(this);
        result.traceID_ = traceID_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hualala.app.wechat.grpc.Common.RequestHeader) {
          return mergeFrom((com.hualala.app.wechat.grpc.Common.RequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hualala.app.wechat.grpc.Common.RequestHeader other) {
        if (other == com.hualala.app.wechat.grpc.Common.RequestHeader.getDefaultInstance()) return this;
        if (!other.getTraceID().isEmpty()) {
          traceID_ = other.traceID_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hualala.app.wechat.grpc.Common.RequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hualala.app.wechat.grpc.Common.RequestHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object traceID_ = "";
      /**
       * <code>optional string traceID = 1;</code>
       */
      public java.lang.String getTraceID() {
        java.lang.Object ref = traceID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          traceID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string traceID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTraceIDBytes() {
        java.lang.Object ref = traceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string traceID = 1;</code>
       */
      public Builder setTraceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string traceID = 1;</code>
       */
      public Builder clearTraceID() {
        
        traceID_ = getDefaultInstance().getTraceID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string traceID = 1;</code>
       */
      public Builder setTraceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        traceID_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestHeader)
    }

    // @@protoc_insertion_point(class_scope:RequestHeader)
    private static final com.hualala.app.wechat.grpc.Common.RequestHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hualala.app.wechat.grpc.Common.RequestHeader();
    }

    public static com.hualala.app.wechat.grpc.Common.RequestHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestHeader>
        PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
      public RequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestHeader> getParserForType() {
      return PARSER;
    }

    public com.hualala.app.wechat.grpc.Common.RequestHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResultHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string traceID = 1;</code>
     */
    java.lang.String getTraceID();
    /**
     * <code>optional string traceID = 1;</code>
     */
    com.google.protobuf.ByteString
        getTraceIDBytes();

    /**
     * <code>optional string code = 2;</code>
     */
    java.lang.String getCode();
    /**
     * <code>optional string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code ResultHeader}
   */
  public  static final class ResultHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResultHeader)
      ResultHeaderOrBuilder {
    // Use ResultHeader.newBuilder() to construct.
    private ResultHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultHeader() {
      traceID_ = "";
      code_ = "";
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResultHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              traceID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hualala.app.wechat.grpc.Common.internal_static_ResultHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hualala.app.wechat.grpc.Common.internal_static_ResultHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hualala.app.wechat.grpc.Common.ResultHeader.class, com.hualala.app.wechat.grpc.Common.ResultHeader.Builder.class);
    }

    public static final int TRACEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object traceID_;
    /**
     * <code>optional string traceID = 1;</code>
     */
    public java.lang.String getTraceID() {
      java.lang.Object ref = traceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string traceID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIDBytes() {
      java.lang.Object ref = traceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <code>optional string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTraceIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceID_);
      }
      if (!getCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTraceIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceID_);
      }
      if (!getCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hualala.app.wechat.grpc.Common.ResultHeader)) {
        return super.equals(obj);
      }
      com.hualala.app.wechat.grpc.Common.ResultHeader other = (com.hualala.app.wechat.grpc.Common.ResultHeader) obj;

      boolean result = true;
      result = result && getTraceID()
          .equals(other.getTraceID());
      result = result && getCode()
          .equals(other.getCode());
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceID().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hualala.app.wechat.grpc.Common.ResultHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResultHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResultHeader)
        com.hualala.app.wechat.grpc.Common.ResultHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hualala.app.wechat.grpc.Common.internal_static_ResultHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hualala.app.wechat.grpc.Common.internal_static_ResultHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hualala.app.wechat.grpc.Common.ResultHeader.class, com.hualala.app.wechat.grpc.Common.ResultHeader.Builder.class);
      }

      // Construct using com.hualala.app.wechat.grpc.Common.ResultHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        traceID_ = "";

        code_ = "";

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hualala.app.wechat.grpc.Common.internal_static_ResultHeader_descriptor;
      }

      public com.hualala.app.wechat.grpc.Common.ResultHeader getDefaultInstanceForType() {
        return com.hualala.app.wechat.grpc.Common.ResultHeader.getDefaultInstance();
      }

      public com.hualala.app.wechat.grpc.Common.ResultHeader build() {
        com.hualala.app.wechat.grpc.Common.ResultHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hualala.app.wechat.grpc.Common.ResultHeader buildPartial() {
        com.hualala.app.wechat.grpc.Common.ResultHeader result = new com.hualala.app.wechat.grpc.Common.ResultHeader(this);
        result.traceID_ = traceID_;
        result.code_ = code_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hualala.app.wechat.grpc.Common.ResultHeader) {
          return mergeFrom((com.hualala.app.wechat.grpc.Common.ResultHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hualala.app.wechat.grpc.Common.ResultHeader other) {
        if (other == com.hualala.app.wechat.grpc.Common.ResultHeader.getDefaultInstance()) return this;
        if (!other.getTraceID().isEmpty()) {
          traceID_ = other.traceID_;
          onChanged();
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hualala.app.wechat.grpc.Common.ResultHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hualala.app.wechat.grpc.Common.ResultHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object traceID_ = "";
      /**
       * <code>optional string traceID = 1;</code>
       */
      public java.lang.String getTraceID() {
        java.lang.Object ref = traceID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          traceID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string traceID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTraceIDBytes() {
        java.lang.Object ref = traceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string traceID = 1;</code>
       */
      public Builder setTraceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string traceID = 1;</code>
       */
      public Builder clearTraceID() {
        
        traceID_ = getDefaultInstance().getTraceID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string traceID = 1;</code>
       */
      public Builder setTraceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        traceID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>optional string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ResultHeader)
    }

    // @@protoc_insertion_point(class_scope:ResultHeader)
    private static final com.hualala.app.wechat.grpc.Common.ResultHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hualala.app.wechat.grpc.Common.ResultHeader();
    }

    public static com.hualala.app.wechat.grpc.Common.ResultHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResultHeader>
        PARSER = new com.google.protobuf.AbstractParser<ResultHeader>() {
      public ResultHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResultHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResultHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResultHeader> getParserForType() {
      return PARSER;
    }

    public com.hualala.app.wechat.grpc.Common.ResultHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestPageHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestPageHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 pageNo = 1;</code>
     */
    int getPageNo();

    /**
     * <code>optional int32 pageSize = 2;</code>
     */
    int getPageSize();
  }
  /**
   * Protobuf type {@code RequestPageHeader}
   */
  public  static final class RequestPageHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestPageHeader)
      RequestPageHeaderOrBuilder {
    // Use RequestPageHeader.newBuilder() to construct.
    private RequestPageHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestPageHeader() {
      pageNo_ = 0;
      pageSize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestPageHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              pageNo_ = input.readInt32();
              break;
            }
            case 16: {

              pageSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hualala.app.wechat.grpc.Common.internal_static_RequestPageHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hualala.app.wechat.grpc.Common.internal_static_RequestPageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hualala.app.wechat.grpc.Common.RequestPageHeader.class, com.hualala.app.wechat.grpc.Common.RequestPageHeader.Builder.class);
    }

    public static final int PAGENO_FIELD_NUMBER = 1;
    private int pageNo_;
    /**
     * <code>optional int32 pageNo = 1;</code>
     */
    public int getPageNo() {
      return pageNo_;
    }

    public static final int PAGESIZE_FIELD_NUMBER = 2;
    private int pageSize_;
    /**
     * <code>optional int32 pageSize = 2;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageNo_ != 0) {
        output.writeInt32(1, pageNo_);
      }
      if (pageSize_ != 0) {
        output.writeInt32(2, pageSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageNo_);
      }
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hualala.app.wechat.grpc.Common.RequestPageHeader)) {
        return super.equals(obj);
      }
      com.hualala.app.wechat.grpc.Common.RequestPageHeader other = (com.hualala.app.wechat.grpc.Common.RequestPageHeader) obj;

      boolean result = true;
      result = result && (getPageNo()
          == other.getPageNo());
      result = result && (getPageSize()
          == other.getPageSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PAGENO_FIELD_NUMBER;
      hash = (53 * hash) + getPageNo();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hualala.app.wechat.grpc.Common.RequestPageHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestPageHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestPageHeader)
        com.hualala.app.wechat.grpc.Common.RequestPageHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hualala.app.wechat.grpc.Common.internal_static_RequestPageHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hualala.app.wechat.grpc.Common.internal_static_RequestPageHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hualala.app.wechat.grpc.Common.RequestPageHeader.class, com.hualala.app.wechat.grpc.Common.RequestPageHeader.Builder.class);
      }

      // Construct using com.hualala.app.wechat.grpc.Common.RequestPageHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pageNo_ = 0;

        pageSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hualala.app.wechat.grpc.Common.internal_static_RequestPageHeader_descriptor;
      }

      public com.hualala.app.wechat.grpc.Common.RequestPageHeader getDefaultInstanceForType() {
        return com.hualala.app.wechat.grpc.Common.RequestPageHeader.getDefaultInstance();
      }

      public com.hualala.app.wechat.grpc.Common.RequestPageHeader build() {
        com.hualala.app.wechat.grpc.Common.RequestPageHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hualala.app.wechat.grpc.Common.RequestPageHeader buildPartial() {
        com.hualala.app.wechat.grpc.Common.RequestPageHeader result = new com.hualala.app.wechat.grpc.Common.RequestPageHeader(this);
        result.pageNo_ = pageNo_;
        result.pageSize_ = pageSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hualala.app.wechat.grpc.Common.RequestPageHeader) {
          return mergeFrom((com.hualala.app.wechat.grpc.Common.RequestPageHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hualala.app.wechat.grpc.Common.RequestPageHeader other) {
        if (other == com.hualala.app.wechat.grpc.Common.RequestPageHeader.getDefaultInstance()) return this;
        if (other.getPageNo() != 0) {
          setPageNo(other.getPageNo());
        }
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hualala.app.wechat.grpc.Common.RequestPageHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hualala.app.wechat.grpc.Common.RequestPageHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pageNo_ ;
      /**
       * <code>optional int32 pageNo = 1;</code>
       */
      public int getPageNo() {
        return pageNo_;
      }
      /**
       * <code>optional int32 pageNo = 1;</code>
       */
      public Builder setPageNo(int value) {
        
        pageNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pageNo = 1;</code>
       */
      public Builder clearPageNo() {
        
        pageNo_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <code>optional int32 pageSize = 2;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>optional int32 pageSize = 2;</code>
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pageSize = 2;</code>
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestPageHeader)
    }

    // @@protoc_insertion_point(class_scope:RequestPageHeader)
    private static final com.hualala.app.wechat.grpc.Common.RequestPageHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hualala.app.wechat.grpc.Common.RequestPageHeader();
    }

    public static com.hualala.app.wechat.grpc.Common.RequestPageHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestPageHeader>
        PARSER = new com.google.protobuf.AbstractParser<RequestPageHeader>() {
      public RequestPageHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestPageHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestPageHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestPageHeader> getParserForType() {
      return PARSER;
    }

    public com.hualala.app.wechat.grpc.Common.RequestPageHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultPageHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResultPageHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 pageNo = 1;</code>
     */
    int getPageNo();

    /**
     * <code>optional int32 pageSize = 2;</code>
     */
    int getPageSize();

    /**
     * <code>optional int32 pageCount = 3;</code>
     */
    int getPageCount();

    /**
     * <code>optional int32 totalSize = 4;</code>
     */
    int getTotalSize();
  }
  /**
   * Protobuf type {@code ResultPageHeader}
   */
  public  static final class ResultPageHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResultPageHeader)
      ResultPageHeaderOrBuilder {
    // Use ResultPageHeader.newBuilder() to construct.
    private ResultPageHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultPageHeader() {
      pageNo_ = 0;
      pageSize_ = 0;
      pageCount_ = 0;
      totalSize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResultPageHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              pageNo_ = input.readInt32();
              break;
            }
            case 16: {

              pageSize_ = input.readInt32();
              break;
            }
            case 24: {

              pageCount_ = input.readInt32();
              break;
            }
            case 32: {

              totalSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hualala.app.wechat.grpc.Common.internal_static_ResultPageHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hualala.app.wechat.grpc.Common.internal_static_ResultPageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hualala.app.wechat.grpc.Common.ResultPageHeader.class, com.hualala.app.wechat.grpc.Common.ResultPageHeader.Builder.class);
    }

    public static final int PAGENO_FIELD_NUMBER = 1;
    private int pageNo_;
    /**
     * <code>optional int32 pageNo = 1;</code>
     */
    public int getPageNo() {
      return pageNo_;
    }

    public static final int PAGESIZE_FIELD_NUMBER = 2;
    private int pageSize_;
    /**
     * <code>optional int32 pageSize = 2;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    public static final int PAGECOUNT_FIELD_NUMBER = 3;
    private int pageCount_;
    /**
     * <code>optional int32 pageCount = 3;</code>
     */
    public int getPageCount() {
      return pageCount_;
    }

    public static final int TOTALSIZE_FIELD_NUMBER = 4;
    private int totalSize_;
    /**
     * <code>optional int32 totalSize = 4;</code>
     */
    public int getTotalSize() {
      return totalSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageNo_ != 0) {
        output.writeInt32(1, pageNo_);
      }
      if (pageSize_ != 0) {
        output.writeInt32(2, pageSize_);
      }
      if (pageCount_ != 0) {
        output.writeInt32(3, pageCount_);
      }
      if (totalSize_ != 0) {
        output.writeInt32(4, totalSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageNo_);
      }
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageSize_);
      }
      if (pageCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageCount_);
      }
      if (totalSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hualala.app.wechat.grpc.Common.ResultPageHeader)) {
        return super.equals(obj);
      }
      com.hualala.app.wechat.grpc.Common.ResultPageHeader other = (com.hualala.app.wechat.grpc.Common.ResultPageHeader) obj;

      boolean result = true;
      result = result && (getPageNo()
          == other.getPageNo());
      result = result && (getPageSize()
          == other.getPageSize());
      result = result && (getPageCount()
          == other.getPageCount());
      result = result && (getTotalSize()
          == other.getTotalSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PAGENO_FIELD_NUMBER;
      hash = (53 * hash) + getPageNo();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (37 * hash) + PAGECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPageCount();
      hash = (37 * hash) + TOTALSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hualala.app.wechat.grpc.Common.ResultPageHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResultPageHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResultPageHeader)
        com.hualala.app.wechat.grpc.Common.ResultPageHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hualala.app.wechat.grpc.Common.internal_static_ResultPageHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hualala.app.wechat.grpc.Common.internal_static_ResultPageHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hualala.app.wechat.grpc.Common.ResultPageHeader.class, com.hualala.app.wechat.grpc.Common.ResultPageHeader.Builder.class);
      }

      // Construct using com.hualala.app.wechat.grpc.Common.ResultPageHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pageNo_ = 0;

        pageSize_ = 0;

        pageCount_ = 0;

        totalSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hualala.app.wechat.grpc.Common.internal_static_ResultPageHeader_descriptor;
      }

      public com.hualala.app.wechat.grpc.Common.ResultPageHeader getDefaultInstanceForType() {
        return com.hualala.app.wechat.grpc.Common.ResultPageHeader.getDefaultInstance();
      }

      public com.hualala.app.wechat.grpc.Common.ResultPageHeader build() {
        com.hualala.app.wechat.grpc.Common.ResultPageHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hualala.app.wechat.grpc.Common.ResultPageHeader buildPartial() {
        com.hualala.app.wechat.grpc.Common.ResultPageHeader result = new com.hualala.app.wechat.grpc.Common.ResultPageHeader(this);
        result.pageNo_ = pageNo_;
        result.pageSize_ = pageSize_;
        result.pageCount_ = pageCount_;
        result.totalSize_ = totalSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hualala.app.wechat.grpc.Common.ResultPageHeader) {
          return mergeFrom((com.hualala.app.wechat.grpc.Common.ResultPageHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hualala.app.wechat.grpc.Common.ResultPageHeader other) {
        if (other == com.hualala.app.wechat.grpc.Common.ResultPageHeader.getDefaultInstance()) return this;
        if (other.getPageNo() != 0) {
          setPageNo(other.getPageNo());
        }
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        if (other.getPageCount() != 0) {
          setPageCount(other.getPageCount());
        }
        if (other.getTotalSize() != 0) {
          setTotalSize(other.getTotalSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hualala.app.wechat.grpc.Common.ResultPageHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hualala.app.wechat.grpc.Common.ResultPageHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pageNo_ ;
      /**
       * <code>optional int32 pageNo = 1;</code>
       */
      public int getPageNo() {
        return pageNo_;
      }
      /**
       * <code>optional int32 pageNo = 1;</code>
       */
      public Builder setPageNo(int value) {
        
        pageNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pageNo = 1;</code>
       */
      public Builder clearPageNo() {
        
        pageNo_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <code>optional int32 pageSize = 2;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>optional int32 pageSize = 2;</code>
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pageSize = 2;</code>
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }

      private int pageCount_ ;
      /**
       * <code>optional int32 pageCount = 3;</code>
       */
      public int getPageCount() {
        return pageCount_;
      }
      /**
       * <code>optional int32 pageCount = 3;</code>
       */
      public Builder setPageCount(int value) {
        
        pageCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pageCount = 3;</code>
       */
      public Builder clearPageCount() {
        
        pageCount_ = 0;
        onChanged();
        return this;
      }

      private int totalSize_ ;
      /**
       * <code>optional int32 totalSize = 4;</code>
       */
      public int getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>optional int32 totalSize = 4;</code>
       */
      public Builder setTotalSize(int value) {
        
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalSize = 4;</code>
       */
      public Builder clearTotalSize() {
        
        totalSize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ResultPageHeader)
    }

    // @@protoc_insertion_point(class_scope:ResultPageHeader)
    private static final com.hualala.app.wechat.grpc.Common.ResultPageHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hualala.app.wechat.grpc.Common.ResultPageHeader();
    }

    public static com.hualala.app.wechat.grpc.Common.ResultPageHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResultPageHeader>
        PARSER = new com.google.protobuf.AbstractParser<ResultPageHeader>() {
      public ResultPageHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResultPageHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResultPageHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResultPageHeader> getParserForType() {
      return PARSER;
    }

    public com.hualala.app.wechat.grpc.Common.ResultPageHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResultHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestPageHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestPageHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultPageHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResultPageHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommons.proto\" \n\rRequestHeader\022\017\n\007trac" +
      "eID\030\001 \001(\t\">\n\014ResultHeader\022\017\n\007traceID\030\001 \001" +
      "(\t\022\014\n\004code\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\"5\n\021Req" +
      "uestPageHeader\022\016\n\006pageNo\030\001 \001(\005\022\020\n\010pageSi" +
      "ze\030\002 \001(\005\"Z\n\020ResultPageHeader\022\016\n\006pageNo\030\001" +
      " \001(\005\022\020\n\010pageSize\030\002 \001(\005\022\021\n\tpageCount\030\003 \001(" +
      "\005\022\021\n\ttotalSize\030\004 \001(\005B%\n\033com.hualala.app." +
      "wechat.grpcB\006Commonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestHeader_descriptor,
        new java.lang.String[] { "TraceID", });
    internal_static_ResultHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResultHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResultHeader_descriptor,
        new java.lang.String[] { "TraceID", "Code", "Message", });
    internal_static_RequestPageHeader_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RequestPageHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestPageHeader_descriptor,
        new java.lang.String[] { "PageNo", "PageSize", });
    internal_static_ResultPageHeader_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResultPageHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResultPageHeader_descriptor,
        new java.lang.String[] { "PageNo", "PageSize", "PageCount", "TotalSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
