spring:
  profiles.active: dohko
---
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://dohko.mysql.001.master.hualala.com:3306/db_shop?useUnicode=true&characterEncoding=utf8&statementInterceptors=brave.mysql.TracingStatementInterceptor
    username: root
    password: hualaladev
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 3
    max-active: 20
    min-idle: 1
    validation-query: SELECT 1
    test-on-borrow: ture
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 1800000
  rabbitmq:
    host: 172.16.0.29
    port: 5672
    username: guest
    password: guest
#    listener:
#      retry:
#        enabled: true
#        max-attempts:
#    template:
#      receive-timeout:
#      reply-timeout:

  # REDIS (RedisProperties)
  redis:
    database: 0
    host: dohko.redis.hualala.com
    port: 6379
    pool:
      max-idle: 1
      min-idle: 1
      max-active: 1
      max-wait: 10000
  redis2:
    database: 0
    host: 172.16.0.27
    port: 20000
    pool:
      max-idle: 1
      min-idle: 1
      max-active: 1
      max-wait: 10000
mybatis:
   config-location: classpath:mybatis-config.xml

grpc:
  port: 6567
  client:
     hosts:
        wechat: localhost:6567
#        wechat: dohko.wechat.service.hualala.com:31558
#        wechat: 172.16.32.45:6567
        idgen: dohko.id.gen.hualala.com:31249
#        sem: localhost:6466
        user: dohko.user.service.hualala.com:31630
        sem: mu.service.short.message.hualala.com:32272
#        shopcrm: 172.16.32.46:6656
#        shopcrm: dohko.shop.crm.service.hualala.com:31537
        shopcrm: dohko.shop.crm.service21.hualala.com:32313
wechat:
  data:
    componentAppID: wx8ed9d715cdd52b1d
    componentAppSecret: 0c79e1fa963cd80cc0be99b20a18faeb
  mq:
      rabbitmq:
#        cacheQrcodeExchange: mu_hll:service:wechat:exchange:cacheQrcode
#        cacheQrcodeQueue: mu_hll:service:wechat:queue:cacheQrcode
        cacheQrcodeExchange: dohko_hll:service:wechat:exchange:cacheQrcode
        cacheQrcodeQueue: dohko_hll:service:wechat:queue:cacheQrcode
        templateMessageExchange: mu_hll:service:wechat:exchange:templateMessage
        templateMessageQueue: mu_hll:service:wechat:queue:templateMessage
  card:
      skuQuantity: mu_hll:service:wechat:card:sku_quantity
  mpID:
    qrcodeDefaultMpID: doulaofangceshi
#redisStock:
#  host: 172.16.0.27
#  port: 19000
#  db: 0
#  pool:
#    maxActive: 2
#    maxWait: 10000
#    maxIdle: 1
#    minIdle: 1
redisSku:
  host: 172.16.0.27
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 10
    minIdle: 1
redisLocker:
  host: 172.16.0.27
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 20
    minIdle: 10

zookeeper:
  zookeeperAddress: 172.16.0.25:2181,172.16.0.26:2181,172.16.0.27:2181  #zookeeper uri  e.g.:127.0.0.1:2181
  serviceName: wechat-card  #服务名称
  basePath: /wechat-service   #服务根路径
  servicePath: /wechat-services  #服务注册路径
  lockPath: /wechat/card/lock  #分布式锁路径

env:
  m:
    domain: https://dohko.m.hualala.com
wechatsdk:
    host: localhost:6567

core:
  zipkin:
    url: http://dohko.zipkin.hualala.com/api/v2/spans   #zipkin server地址，采集到的数据发送至此。线上地址用哪个，上线前咨询运维同学（叶志勤）
    serviceName: wechat-service                      #当前服务名称
    traceSampler: 1.0                                  #采样比率，1.0表示百分百，刚上线使用建议1.0，后续系统性能稳定建议 0.1。
    enable: true                                        #开关：是否使用zipkin，如果不设置（或者false），zipkin不能使用

---
spring:
  profiles: mu
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://dohko.mysql.001.master.hualala.com:3306/db_shop?useUnicode=true&characterEncoding=utf8&statementInterceptors=brave.mysql.TracingStatementInterceptor
    username: root
    password: hualaladev
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 3
    max-active: 20
    min-idle: 1
    validation-query: SELECT 1
    test-on-borrow: ture
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 1800000

  rabbitmq:
    host: 172.16.0.29
    port: 5672
    username: guest
    password: guest
#    listener:
#      retry:
#        enabled: true
#        max-attempts:
#    template:
#      receive-timeout:
#      reply-timeout:

  # REDIS (RedisProperties)
  redis:
    database: 0
    host: dohko.redis.hualala.com
    port: 6379
    pool:
      max-idle: 1
      min-idle: 1
      max-active: 1
      max-wait: 10000
  redis2:
    database: 0
    host: 172.16.0.27
    port: 20000
    pool:
      max-idle: 1
      min-idle: 1
      max-active: 1
      max-wait: 10000
mybatis:
   config-location: classpath:mybatis-config.xml

grpc:
  port: 6567
  client:
     hosts:
        wechat: 172.16.32.45:6567
#        wechat: dohko.wechat.service.hualala.com:31558
#        wechat: 192.168.5.204:6567
        idgen: dohko.id.gen.hualala.com:31249
#        sem: localhost:6466
        sem: dohko.service.short.message.hualala.com:31524
        shopcrm: 172.16.32.46:6656
#        shopcrm: dohko.shop.crm.service.hualala.com:31537
        user: dohko.user.service.hualala.com:31630
wechat:
  data:
    componentAppID: wx8ed9d715cdd52b1d
    componentAppSecret: 0c79e1fa963cd80cc0be99b20a18faeb
  mq:
      rabbitmq:
        cacheQrcodeExchange: mu_hll:service:wechat:exchange:cacheQrcode
        cacheQrcodeQueue: mu_hll:service:wechat:queue:cacheQrcode
        templateMessageExchange: mu_hll:service:wechat:exchange:templateMessage
        templateMessageQueue: mu_hll:service:wechat:queue:templateMessage
  card:
      skuQuantity: mu_hll:service:wechat:card:sku_quantity
  mpID:
    qrcodeDefaultMpID: doulaofangceshi
#redisStock:
#  host: 172.16.0.27
#  port: 19000
#  db: 0
#  pool:
#    maxActive: 2
#    maxWait: 10000
#    maxIdle: 1
#    minIdle: 1
redisSku:
  host: 172.16.0.27
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 10
    minIdle: 1
redisLocker:
  host: 172.16.0.27
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 20
    minIdle: 10

zookeeper:
  zookeeperAddress: 172.16.0.25:2181,172.16.0.26:2181,172.16.0.27:2181  #zookeeper uri  e.g.:127.0.0.1:2181
  serviceName: wechat-card  #服务名称
  basePath: /wechat-service   #服务根路径
  servicePath: /wechat-services  #服务注册路径
  lockPath: /wechat/card/lock  #分布式锁路径

env:
  m:
    domain: https://dohko.m.hualala.com

core:
  zipkin:
    url: http://dohko.zipkin.hualala.com/api/v2/spans   #zipkin server地址，采集到的数据发送至此。线上地址用哪个，上线前咨询运维同学（叶志勤）
    serviceName: wechat-service                      #当前服务名称
    traceSampler: 1.0                                  #采样比率，1.0表示百分百，刚上线使用建议1.0，后续系统性能稳定建议 0.1。
    enable: true                                        #开关：是否使用zipkin，如果不设置（或者false），zipkin不能使用
wechatsdk:
    host: dohko.wechat.service.hualala.com:31558

---
spring:
  profiles: dohko
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
      url: jdbc:mysql://dohko.mysql.001.master.hualala.com:3306/db_shop?useUnicode=true&characterEncoding=utf8&statementInterceptors=brave.mysql.TracingStatementInterceptor
      username: root
      password: hualaladev
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 3
      max-active: 20
      min-idle: 1
      validation-query: SELECT 1
      test-on-borrow: ture
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 1800000
  rabbitmq:
    host: 172.16.0.29
    port: 5672
    username: guest
    password: guest

  # REDIS (RedisProperties)
  redis:
    database: 0
    host: dohko.redis.hualala.com
    port: 6379
    pool:
      max-idle: 1
      min-idle: 1
      max-active: 1
      max-wait: 10000
  redis2:
    database: 0
    host: 172.16.0.27
    port: 20000
    pool:
      max-idle: 1
      min-idle: 1
      max-active: 1
      max-wait: 10000
mybatis:
   config-location: classpath:mybatis-config.xml

grpc:
  port: 6567
  client:
     hosts:
        #wechat: localhost:6567
        wechat: dohko.wechat.service.hualala.com:31558
        idgen: dohko.id.gen.hualala.com:31249
        sem: dohko.service.short.message.hualala.com:31524
#        shopcrm: dohko.shop.crm.service.hualala.com:31537
        shopcrm: dohko.shop.crm.service21.hualala.com:32313 # 会员2.1 dohko环境
        user: dohko.user.service.hualala.com:31630
wechat:
  data:
#    componentAppID: wx431ecb8eae767f0c  #mu环境
    componentAppID: wx8ed9d715cdd52b1d  #dohko环境
    componentAppSecret: 0c79e1fa963cd80cc0be99b20a18faeb
  mq:
      rabbitmq:
        cacheQrcodeExchange: dohko_hll:service:wechat:exchange:cacheQrcode
        cacheQrcodeQueue: dohko_hll:service:wechat:queue:cacheQrcode
        templateMessageExchange: dohko_hll:service:wechat:exchange:templateMessage
        templateMessageQueue: dohko_hll:service:wechat:queue:templateMessage
  card:
      skuQuantity: dohko_hll:service:wechat:card:sku_quantity
  mpID:
    qrcodeDefaultMpID: doulaofangceshi
#redisStock:
#  host: 172.16.0.27
#  port: 19000
#  db: 0
#  pool:
#    maxActive: 50
#    maxWait: 10000
#    maxIdle: 10
#    minIdle: 1
redisSku:
  host: 172.16.0.27
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 10
    minIdle: 1
redisLocker:
  host: 172.16.0.27
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 20
    minIdle: 10

zookeeper:
  zookeeperAddress: 172.16.0.25:3181,172.16.0.26:3181,172.16.0.27:3181  #zookeeper uri  e.g.:127.0.0.1:2181
  serviceName: wechat-card  #服务名称
  basePath: /wechat-service   #服务根路径
  servicePath: /wechat-services  #服务注册路径
  lockPath: /wechat/card/lock  #分布式锁路径

env:
  m:
    domain: https://dohko.m.hualala.com

core:
  zipkin:
    url: http://dohko.zipkin.hualala.com/api/v2/spans   #zipkin server地址，采集到的数据发送至此。线上地址用哪个，上线前咨询运维同学（叶志勤）
    serviceName: wechat-service                      #当前服务名称
    traceSampler: 1.0                                  #采样比率，1.0表示百分百，刚上线使用建议1.0，后续系统性能稳定建议 0.1。
    enable: true                                        #开关：是否使用zipkin，如果不设置（或者false），zipkin不能使用
wechatsdk:
    host: dohko.wechat.service.hualala.com:31558
---
spring:
  profiles: pre
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://dohko.mysql.001.master.hualala.com:3306/db_shop?useUnicode=true&characterEncoding=utf8&statementInterceptors=brave.mysql.TracingStatementInterceptor
    username: root
    password: hualaladev
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 3
    max-active: 20
    min-idle: 1
    validation-query: SELECT 1
    test-on-borrow: ture
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 1800000
  rabbitmq:
    host: 172.16.0.29
    port: 5672
    username: guest
    password: guest

  # REDIS (RedisProperties)
  redis:
    database: 0
    host: dohko.redis.hualala.com
    port: 6379
    pool:
      max-idle: 1
      min-idle: 1
      max-active: 1
      max-wait: 10000
  # REDIS (RedisProperties)
  redis2:
    database: 0
    host: 172.16.0.27
    port: 20000
    pool:
      max-idle: 1
      min-idle: 1
      max-active: 1
      max-wait: 10000

mybatis:
   config-location: classpath:mybatis-config.xml

grpc:
  port: 6567
  client:
     hosts:
        wechat: pre.wechat.service.hualala.com:31558
#        idgen: dohko.id.gen.hualala.com:31249
        sem: pre.service.short.message.hualala.com:31524
        shopcrm: pre.shop.crm.service.hualala.com:31537

wechat:
  data:
    componentAppID: wx8ed9d715cdd52b1d
    componentAppSecret: 0c79e1fa963cd80cc0be99b20a18faeb
  mq:
      rabbitmq:
        cacheQrcodeExchange: pre_hll:service:wechat:exchange:cacheQrcode
        cacheQrcodeQueue: pre_hll:service:wechat:queue:cacheQrcode
        templateMessageExchange: pre_hll:service:wechat:exchange:templateMessage
        templateMessageQueue: pre_hll:service:wechat:queue:templateMessage
  card:
      skuQuantity: pre_hll:service:wechat:card:sku_quantity
  mpID:
      qrcodeDefaultMpID: hualala_dld
#redisStock:
#  host: 172.16.0.27
#  port: 19000
#  db: 0
#  pool:
#    maxActive: 50
#    maxWait: 10000
#    maxIdle: 10
#    minIdle: 1
redisSku:
  host: 172.16.0.27
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 10
    minIdle: 1
redisLocker:
  host: 172.16.0.27
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 20
    minIdle: 10


zookeeper:
  zookeeperAddress: 172.16.0.25:3181,172.16.0.26:3181,172.16.0.27:3181  #zookeeper uri  e.g.:127.0.0.1:2181
  serviceName: wechat-card  #服务名称
  basePath: /wechat-service   #服务根路径
  servicePath: /wechat-services  #服务注册路径
  lockPath: /wechat/card/lock  #分布式锁路径

env:
  m:
    domain: https://dohko.m.hualala.com

core:
  zipkin:
    url: http://dohko.zipkin.hualala.com/api/v2/spans   #zipkin server地址，采集到的数据发送至此。线上地址用哪个，上线前咨询运维同学（叶志勤）
    serviceName: wechat-service                      #当前服务名称
    traceSampler: 1.0                                  #采样比率，1.0表示百分百，刚上线使用建议1.0，后续系统性能稳定建议 0.1。
    enable: true                                        #开关：是否使用zipkin，如果不设置（或者false），zipkin不能使用
wechatsdk:
    host: pre.wechat.service.hualala.com:31558

---
spring:
  profiles: production
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://mysql.shop.001.master.hualala.com:6350/db_shop?useUnicode=true&characterEncoding=utf8&statementInterceptors=brave.mysql.TracingStatementInterceptor
    username: myhualashopol
    password: gppwd@dldshopol
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 100
    min-idle: 2
    validation-query: SELECT 1
    test-on-borrow: ture
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    min-evictable-idle-time-millis: 1800000
  rabbitmq:
    username: admin
    password: hualalaadmin
    host: inner.rabbitmq.hualala.com
    port: 5672
  # REDIS (RedisProperties)
  redis:
    database: 0
    host: redis1.api.hualala.com
    port: 21379
    pool:
      max-idle: 50
      min-idle: 30
      max-active: 200
      max-wait: 10000
        # REDIS (RedisProperties)
  redis2:
    database: 0
    host: sjhl.codis.hualala.com
    port: 20000
    pool:
      max-idle: 50
      min-idle: 30
      max-active: 200
      max-wait: 10000
mybatis:
   config-location: classpath:mybatis-config.xml
grpc:
  port: 6567
  client:
     hosts:
#        idgen: id.gen.hualala.com:32243
        sem: service.short.message.hualala.com:7081
        wechat: wechat.service.hualala.com:32263
#        shopcrm: shop.crm.service.hualala.com:32244
        shopcrm: shop.crm.service21.hualala.com:32306
wechat:
  data:
      componentAppID: wx01482fd383628bee
      componentAppSecret: 0c79e1fa963cd80cc0be99b20a18faeb
  mq:
      rabbitmq:
        cacheQrcodeExchange: hll:service:wechat:exchange:cacheQrcode
        cacheQrcodeQueue: hll:service:wechat:queue:cacheQrcode
        templateMessageExchange: hll:service:wechat:exchange:templateMessage
        templateMessageQueue: hll:service:wechat:queue:templateMessage
  card:
      skuQuantity: hll:service:wechat:card:sku_quantity
  mpID:
      qrcodeDefaultMpID: hualala_dld
#redisStock:
#    host: sjhl.codis.hualala.com
#    port: 19000
#    db: 0
#    pool:
#      maxActive: 50
#      maxWait: 10000
#      maxIdle: 10
#      minIdle: 1
redisSku:
  host: sjhl.codis.hualala.com
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 20
    minIdle: 10
redisLocker:
  host: sjhl.codis.hualala.com
  port: 19000
  db: 0
  pool:
    maxActive: 50
    maxWait: 10000
    maxIdle: 20
    minIdle: 10
zookeeper:
  zookeeperAddress: 192.168.2.64:2181,192.168.2.65:2181,192.168.2.69:2181,192.168.2.67:2181,192.168.2.68:2181  #zookeeper uri
  serviceName: wechat-card  #服务名称
  basePath: /wechat-service   #服务根路径
  servicePath: /wechat-services  #服务注册路径
  lockPath: /wechat/card/lock  #分布式锁路径
env:
  m:
    domain: https://m.hualala.com
core:
  zipkin:
    url: http://zipkin.sm.hualala.com/api/v2/spans   #zipkin server首鸣机房地址，采集到的数据发送至此。
    serviceName: store-api-portal                      #当前服务名称
    traceSampler: 1.0                                  #采样比率，1.0表示百分百，刚上线使用建议1.0，后续系统性能稳定建议 0.1。
    enable: true                                        #开关：是否使用zipkin，如果不设置（或者false），zipkin不能使用
wechatsdk:
    host: wechat.service.hualala.com:32263